#!/usr/bin/env bash

# Hyprland/Wayland Packages
 
 sudo apt install -y cliphist grim acpica-tools wofi swappy thunar thunar-archive-plugin thunar-volman file-roller terminator gimp kcalc microsoft-edge-stable bleachbit qimgv dialog blueman avahi-daemon acpi qt5-style-kvantum
 acpid kitty pavucontrol pipewire playerctl polkitd python3-requests python3-pip slurp dunst waybar wget wl-clipboard wlogout xdg-user-dirs xdg-utils yad brightnessctl btop cava mousepad mpv mpv-mpris pamixer

sudo systemctl enable avahi-daemon
sudo systemctl enable acpid
